FROM ubuntu:latest
MAINTAINER Hessel Tjeerdsma "hesseltjeerdsma@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential wget
COPY . /app
WORKDIR /app
RUN wget --no-cache https://raw.githubusercontent.com/HesselTjeerdsma/PacmanFInder/master/lamdba-files/app.py
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
